In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 12
COLS_PER_MONTH = 4
SHEET_SEARCH_STRING = "past due balances"
ARREARAGE_SEARCH_STRING = "past-due balances by customer class"
KLI_SEARCH_STRING = "past-due balances for known low-income household"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.AVISTA.code}_{YEAR}_Q{QUARTER}.xlsx"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, COLS_PER_MONTH, ARREARAGE_SEARCH_STRING
)
kli_arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(df, NUM_MONTHS, COLS_PER_MONTH, KLI_SEARCH_STRING)

# Arrearages

In [3]:
date_to_zip_offset = 1
source_date_format = "%Y-%m-%d %H:%M:%S"

arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [4]:
arrearages

shape: (105, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 01 2024   ┆ 01 2024   ┆ 01 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 98620    ┆ 3867.35   ┆ 2171.71   ┆ 9158.78   ┆ … ┆ 1397.29   ┆ 1637.4    ┆ 4619.57   ┆ 7654.26   │
│ 98648    ┆ 794.86    ┆ 747.16    ┆ 1769.03   ┆ … ┆ 504.58    ┆ 370.39    ┆ 1343.33   ┆ 2218.3    │
│ 98857    ┆ 361.4     ┆ 0.0       ┆ 155.01    ┆ … ┆ 171.95    ┆ 0.0       ┆ 0.0       ┆ 171.95    │
│ 99001    ┆ 11043.49  ┆ 6788.47   ┆ 21819.63  ┆ … ┆ 6747.13   ┆ 7819.2    ┆ 12961.63  ┆ 27527.96  │
│ 99003    ┆ 9072.52   ┆ 2849.95   ┆ 11997.63  ┆ … ┆ 6941.23   ┆ 2723.94   ┆ 6607.38   ┆ 16272.55  │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 99341    ┆ 4496.91   ┆ 3786.77   ┆ 7079.44   ┆ … ┆ 3390.82   ┆ 427.85    ┆ 2814.73   ┆ 6633.4    │
│ 99344    ┆ 28511.08  ┆ 16202.24  ┆ 30151.81  ┆ … ┆ 21296.25  ┆ 15129.75  ┆ 27015.69  ┆ 63441.69  │
│ 99371    ┆ 1476.51   ┆ 1770.39   ┆ 1496.11   ┆ … ┆ 1901.93   ┆ 960.3     ┆ 999.57    ┆ 3861.8    │
│ 99402    ┆ 4188.17   ┆ 1412.13   ┆ 8688.61   ┆ … ┆ 3516.3    ┆ 2167.92   ┆ 2284.75   ┆ 7968.97   │
│ 99403    ┆ 28085.8   ┆ 13166.73  ┆ 125550.63 ┆ … ┆ 11577.36  ┆ 44609.11  ┆ 51963.25  ┆ 108149.72 │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
arrearages.sum()

shape: (1, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 01 2024   ┆ 01 2024   ┆ 01 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10407700 ┆ 1.9802e6  ┆ 1.2420e6  ┆ 2.8916e6  ┆ … ┆ 1.6971e6  ┆ 1.1984e6  ┆ 1.9033e6  ┆ 4798848.6 │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# KLI Arrearages

In [6]:
date_to_zip_offset = 1
source_date_format = "%Y-%m-%d %H:%M:%S"

kli_arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    kli_arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [7]:
kli_arrearages.sum()

shape: (1, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 01 2024   ┆ 01 2024   ┆ 01 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10407700 ┆ 359026.37 ┆ 385153.04 ┆ 1.4268e6  ┆ … ┆ 237883.09 ┆ 241488.12 ┆ 792695.0  ┆ 2.5441e6  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Save Output

In [8]:
nwec.utility_reporting.arrearages.save_processed_arrearages(
    arrearages, kli_arrearages, NUM_MONTHS, Utility.AVISTA, YEAR, QUARTER
)