In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 12
COLS_PER_MONTH = 4
SHEET_SEARCH_STRING = "past due balances"
ARREARAGE_SEARCH_STRING = "past-due balances by customer class"
KLI_SEARCH_STRING = "past-due balances for known low-income household"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.AVISTA.code}_{YEAR}_Q{QUARTER}.xlsx"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, COLS_PER_MONTH, ARREARAGE_SEARCH_STRING
)
kli_arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(df, NUM_MONTHS, COLS_PER_MONTH, KLI_SEARCH_STRING)

# Arrearages

In [3]:
date_to_zip_offset = 1
source_date_format = "%Y-%m-%d %H:%M:%S"

arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [4]:
arrearages.sum()

shape: (1, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 01 2024   ┆ 01 2024   ┆ 01 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10407700 ┆ 1.9802e6  ┆ 1.2420e6  ┆ 2.8916e6  ┆ … ┆ 1.6971e6  ┆ 1.1984e6  ┆ 1.9033e6  ┆ 4798848.6 │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# KLI Arrearages

In [5]:
date_to_zip_offset = 1
source_date_format = "%Y-%m-%d %H:%M:%S"

kli_arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    kli_arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [6]:
kli_arrearages.sum()

shape: (1, 49)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 01 2024   ┆ 01 2024   ┆ 01 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10407700 ┆ 359026.37 ┆ 385153.04 ┆ 1.4268e6  ┆ … ┆ 237883.09 ┆ 241488.12 ┆ 792695.0  ┆ 2.5441e6  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Save Output

In [7]:
nwec.utility_reporting.arrearages.save_processed_arrearages(
    arrearages, kli_arrearages, NUM_MONTHS, Utility.AVISTA, YEAR, QUARTER
)