In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 3
COLS_PER_MONTH = 8
KLI_COLS_PER_MONTH = 4
SHEET_SEARCH_STRING = "Past Due Balances"
ARREARAGE_SEARCH_STRING = "Past-due balances by customer class"
KLI_SEARCH_STRING = "known low-income"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.NWNG.code}_{YEAR}_Q{QUARTER}.xlsx"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, COLS_PER_MONTH, ARREARAGE_SEARCH_STRING
)
kli_arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, KLI_COLS_PER_MONTH, KLI_SEARCH_STRING
)

# Arrearages

In [3]:
date_to_zip_offset = 1
source_date_format = "%b %Y"

arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [4]:
arrearages.sum()

shape: (1, 25)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 30 Day    ┆ 60 Days   ┆   ┆ 90 Days + ┆ 90 Days + ┆ Total Arr ┆ Total     │
│ i32      ┆ Amt       ┆ Count     ┆ Amt       ┆   ┆ Amt       ┆ Count     ┆ earages   ┆ Count     │
│          ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4234744  ┆ 214004.49 ┆ 3135.0    ┆ 111586.82 ┆ … ┆ 207280.39 ┆ 3158.0    ┆ 829954.93 ┆ 8321.0    │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# KLI Arrearages

In [5]:
date_to_zip_offset = 1
source_date_format = "%b %Y"

kli_arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    kli_arrearages, NUM_MONTHS, KLI_COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [6]:
kli_arrearages.sum()

shape: (1, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆   ┆ 30 Days   ┆ 60 Days   ┆ 90 Days + ┆ Total Arr │
│ i32      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ earages   │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 4234744  ┆ 2011.63   ┆ 2542.58   ┆ 8587.61   ┆ … ┆ 563.34    ┆ 476.33    ┆ 3131.49   ┆ 4171.16   │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Save Output

In [7]:
nwec.utility_reporting.arrearages.save_processed_arrearages(
    arrearages, kli_arrearages, NUM_MONTHS, Utility.NWNG, YEAR, QUARTER
)