In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 3
COLS_PER_MONTH = 5
SHEET_SEARCH_STRING = "Arrears"
ARREARAGE_SEARCH_STRING = "Past-due balances"
KLI_SEARCH_STRING = "known low-income"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.PAC.code}_{YEAR}_Q{QUARTER}.xlsx"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, COLS_PER_MONTH, ARREARAGE_SEARCH_STRING
)
kli_arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(df, NUM_MONTHS, COLS_PER_MONTH, KLI_SEARCH_STRING)

# Arrearages

In [3]:
date_to_zip_offset = 1
source_date_format = "%Y%m"

arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [4]:
arrearages.sum()

shape: (1, 16)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ COUNT     ┆ DAYS 31   ┆ DAYS 61   ┆   ┆ DAYS 31   ┆ DAYS 61   ┆ DAYS 91+  ┆ ARREARS   │
│ i32      ┆ ---       ┆ 60        ┆ 90        ┆   ┆ 60        ┆ 90        ┆ ---       ┆ ---       │
│          ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│          ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3566098  ┆ 20419.0   ┆ 1.9331e6  ┆ 1.2369e6  ┆ … ┆ 2.3343e6  ┆ 909055.65 ┆ 2.6605e6  ┆ 5.9039e6  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# KLI Arrearages

In [5]:
date_to_zip_offset = 1
source_date_format = "%Y%m"

kli_arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    kli_arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [6]:
kli_arrearages.sum()

shape: (1, 16)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ COUNT     ┆ DAYS 31   ┆ DAYS 61   ┆   ┆ DAYS 31   ┆ DAYS 61   ┆ DAYS 91+  ┆ ARREARS   │
│ i32      ┆ ---       ┆ 60        ┆ 90        ┆   ┆ 60        ┆ 90        ┆ ---       ┆ ---       │
│          ┆ f64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│          ┆           ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3170370  ┆ 3956.0    ┆ 357131.84 ┆ 323755.09 ┆ … ┆ 504665.39 ┆ 252381.14 ┆ 913707.94 ┆ 1.6708e6  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Save Output

In [7]:
nwec.utility_reporting.arrearages.save_processed_arrearages(
    arrearages, kli_arrearages, NUM_MONTHS, Utility.PAC, YEAR, QUARTER
)