In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 3
COLS_PER_MONTH = 4
SHEET_SEARCH_STRING = "Past Due Balances"
ARREARAGE_SEARCH_STRING = "Past-due balances by customer class and number of days"
KLI_SEARCH_STRING = "past-due balances for known low-income"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.PSE.code}_{YEAR}_Q{QUARTER}.xlsx"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(
    df, NUM_MONTHS, COLS_PER_MONTH, ARREARAGE_SEARCH_STRING
)
kli_arrearages = nwec.utility_reporting.arrearages.get_arrearages_df(df, NUM_MONTHS, COLS_PER_MONTH, KLI_SEARCH_STRING)

# Arrearages

In [4]:
date_to_zip_offset = 0
source_date_format = "%Y-%m-%d %H:%M:%S"

arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [5]:
arrearages.sum()

shape: (1, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 31 - 60   ┆ 61 - 90   ┆ 91+ Days  ┆   ┆ 31 - 60   ┆ 61 - 90   ┆ 91+ Days  ┆ Total Arr │
│ i32      ┆ Days      ┆ Days      ┆ ---       ┆   ┆ Days      ┆ Days      ┆ ---       ┆ earages   │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│          ┆ f64       ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22503272 ┆ 1.1609e7  ┆ 8431952.2 ┆ 6.6795e7  ┆ … ┆ 1.2009e7  ┆ 7.9054e6  ┆ 5.9924e7  ┆ 1.1351e8  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# KLI Arrearages

In [6]:
date_to_zip_offset = 0
source_date_format = "%Y-%m-%d %H:%M:%S"

kli_arrearages = nwec.utility_reporting.arrearages.combine_arrearage_year_vintage_cols(
    kli_arrearages, NUM_MONTHS, COLS_PER_MONTH, date_to_zip_offset, source_date_format
)

In [7]:
kli_arrearages.sum()

shape: (1, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Zip Code ┆ 10 2024   ┆ 10 2024   ┆ 10 2024   ┆ … ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   ┆ 12 2024   │
│ ---      ┆ 31 - 60   ┆ 61 - 90   ┆ 91+ Days  ┆   ┆ 31 - 60   ┆ 61 - 90   ┆ 91+ Days  ┆ Total Arr │
│ i32      ┆ Days      ┆ Days      ┆ ---       ┆   ┆ Days      ┆ Days      ┆ ---       ┆ earages   │
│          ┆ ---       ┆ ---       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ ---       │
│          ┆ f64       ┆ f64       ┆           ┆   ┆ f64       ┆ f64       ┆           ┆ f64       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 21913360 ┆ 2406662.5 ┆ 2.0332e6  ┆ 1.8051e7  ┆ … ┆ 2.3689e6  ┆ 1.8889e6  ┆ 1.6674e7  ┆ 2.5629e7  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Save Output

In [8]:
nwec.utility_reporting.arrearages.save_processed_arrearages(
    arrearages, kli_arrearages, NUM_MONTHS, Utility.PSE, YEAR, QUARTER
)