In [9]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 12
COLS_PER_MONTH = 1
SHEET_SEARCH_STRING = "disconnections"
NUM_DISCONNECTIONS_SEARCH_STRING = "number of disconnections"
NUM_NOTICES_SEARCH_STRING = "number of customers by customer class receiving disconnection notices"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.AVISTA.code}_{YEAR}_Q{QUARTER}.xlsx"
source_date_format = "%Y-%m-%d %H:%M:%S"

In [6]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_DISCONNECTIONS_SEARCH_STRING)
disconnections = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [7]:
disconnections

shape: (322, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ column_4  ┆ column_5  ┆ column_6  ┆ column_7  ┆ … ┆ column_12 ┆ column_13 ┆ column_14 ┆ column_1 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 5        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Item a)   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Number of ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Disconnec ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ tio…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ 2024-02-0 ┆ 2024-03-0 ┆ 2024-04-0 ┆ … ┆ 2024-09-0 ┆ 2024-10-0 ┆ 2024-11-0 ┆ 2024-12- │
│ 1         ┆ 1         ┆ 1         ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆ 01       │
│ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00 │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 1         ┆ null     │
│ null      ┆ null      ┆ 1         ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 731       ┆ 1037      ┆ 1281      ┆ 1204      ┆ … ┆ 947       ┆ 940       ┆ 661       ┆ 795      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Number of Disconnections

# Number of Disconnection Notices

In [10]:
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_NOTICES_SEARCH_STRING)
notices = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [11]:
notices

shape: (322, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ column_42 ┆ column_43 ┆ column_44 ┆ column_45 ┆ … ┆ column_50 ┆ column_51 ┆ column_52 ┆ column_5 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 3        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Item c)   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Number of ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Customers ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ by…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ 2024-02-0 ┆ 2024-03-0 ┆ 2024-04-0 ┆ … ┆ 2024-09-0 ┆ 2024-10-0 ┆ 2024-11-0 ┆ 2024-12- │
│ 1         ┆ 1         ┆ 1         ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆ 01       │
│ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00 │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 3         ┆ 5         ┆ 8         ┆ 7         ┆ … ┆ 2         ┆ 5         ┆ 2         ┆ 5        │
│ 1         ┆ 1         ┆ 2         ┆ 3         ┆ … ┆ 1         ┆ 2         ┆ 2         ┆ 2        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘