In [1]:
import polars as pl

import nwec.utility_reporting.arrearages
import nwec.utils.excel
from nwec.constants import RAW_UTILITY_DATA, Utility

YEAR = 2024
QUARTER = 4
NUM_MONTHS = 12
COLS_PER_MONTH = 1
SHEET_SEARCH_STRING = "disconnections"
NUM_DISCONNECTIONS_SEARCH_STRING = "number of disconnections"
NUM_NOTICES_SEARCH_STRING = "number of customers by customer class receiving disconnection notices"
spreadsheet = RAW_UTILITY_DATA / str(YEAR) / f"{Utility.CNG.code}_{YEAR}_Q{QUARTER}.xlsx"
source_date_format = "%Y-%m-%d %H:%M:%S"

In [2]:
sheet_index = nwec.utils.excel.get_sheet_index_from_name(spreadsheet, SHEET_SEARCH_STRING)
df = pl.read_excel(spreadsheet, sheet_id=sheet_index, has_header=False)
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_DISCONNECTIONS_SEARCH_STRING)
disconnections = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [3]:
disconnections

shape: (566, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ column_3  ┆ column_4  ┆ column_5  ┆ column_6  ┆ … ┆ column_11 ┆ column_12 ┆ column_13 ┆ column_1 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 4        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Item a)   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Number of ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Disconnec ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ tio…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ 2024-02-0 ┆ 2024-03-0 ┆ 2024-04-0 ┆ … ┆ 2024-09-0 ┆ 2024-10-0 ┆ 2024-11-0 ┆ 2024-12- │
│ 1         ┆ 1         ┆ 1         ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆ 01       │
│ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00 │
│ null      ┆ null      ┆ 0         ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ 1         ┆ 2         ┆ … ┆ null      ┆ 1         ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Number of Disconnections

# Number of Disconnection Notices

In [4]:
_, start_index = nwec.utils.excel.find_cell_by_string(df, NUM_NOTICES_SEARCH_STRING)
notices = df.select(df.columns[start_index : start_index + NUM_MONTHS * COLS_PER_MONTH])

In [5]:
notices

shape: (566, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ column_24 ┆ column_25 ┆ column_26 ┆ column_27 ┆ … ┆ column_32 ┆ column_33 ┆ column_34 ┆ column_3 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 5        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Item c)   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Number of ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Customers ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ by…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Zip Code  ┆ Customer  ┆ 2024-01-0 ┆ 2024-02-0 ┆ … ┆ 2024-07-0 ┆ 2024-08-0 ┆ 2024-09-0 ┆ 2024-10- │
│           ┆ Class     ┆ 1         ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆ 01       │
│           ┆           ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00  ┆ 00:00:00 │
│ 97701     ┆ RESIDENT  ┆ 3         ┆ 1         ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 98220     ┆ RESIDENT  ┆ 11        ┆ 6         ┆ … ┆ null      ┆ 2         ┆ 2         ┆ 2        │
│ 98221     ┆ RESIDENT  ┆ 213       ┆ 121       ┆ … ┆ 130       ┆ 93        ┆ 98        ┆ 76       │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘